name: Configuration

on:
  push:
    branches: 
        - main
        - development

env:
  BUILD_CONFIGURATION: 'Release'
  DOTNET_VERSION: '7.x'
  RestoreBuildProjects: '.\src'
  TestProjects: '.\src'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install DotNet SonarScanner Global Tool
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Restore dependencies
      run: dotnet restore ${{ env.RestoreBuildProjects }}

    - name: SonarScanner Start
      run: dotnet sonarscanner begin \
              /o:svartis \
              /k:svartis_audio-guestbook-net \
              /d:sonar.host.url=https://sonarcloud.io
              /d:sonar.token="${{ env.SONAR_TOKEN }}"
      
    - name: Build
      run: dotnet build ${{ env.RestoreBuildProjects }} --configuration '${{ env.BUILD_CONFIGURATION }}' --no-restore
      
    - name: Test
      run: dotnet test ${{ env.TestProjects }} --configuration '${{ env.BUILD_CONFIGURATION }}' --no-restore --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --collect="XPlat Code Coverage"

    - name: SonarScanner End
      run: dotnet sonarscanner end \
              /d:sonar.token="${{ env.SONAR_TOKEN }}"
