name: Build Test Analyze

on:
  push:
    branches: 
        - main

env:
  BUILD_CONFIGURATION: 'Release'
  DOTNET_VERSION: '7.x'
  RestoreBuildProjects: './src'
  TestProjects: './src'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu' # Alternative distribution options are available.

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install DotNet SonarScanner Global Tool
      run: dotnet tool install --global dotnet-sonarscanner

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.RestoreBuildProjects }}

    - name: SonarScanner Start
      run: dotnet sonarscanner begin /o:svartis /k:svartis_audio-guestbook-net /d:sonar.host.url=https://sonarcloud.io /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml /d:sonar.cs.vstest.reportsPaths=**/*.trx

    - name: Build
      run: dotnet build ${{ env.RestoreBuildProjects }} --configuration '${{ env.BUILD_CONFIGURATION }}' --no-restore
      
    - name: Test
      run: dotnet test ${{ env.TestProjects }} --configuration '${{ env.BUILD_CONFIGURATION }}' --no-restore --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --collect="XPlat Code Coverage"

    - name: SonarScanner End
      run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
